services:
  dagster-dagit:
    container_name: dagit-container
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3333:3333
  dagster-daemon:
    container_name: daemon-container
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "dagster-daemon run"
  dagster-postgres:
    container_name: postgres-container
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    #volumes:
    #  - ./datafile.sql:/docker-entrypoint-initdb.d/datafile.sql

  metabase:
      container_name: metabase-container
      build:
        context: .
        dockerfile: docker/metabase.Dockerfile
      restart: on-failure
      ports:
        - 3000:3000
      environment:
        MB_DB_TYPE: postgres
        MB_DB_PORT: 5432
        MB_DB_DBNAME: postgres
        MB_DB_USER: postgres
        MB_DB_PASS: secret
        MB_DB_HOST: dagster-postgres
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 10s
        timeout: 10s
        retries: 10
        start_period: 30s
      depends_on:
        - dagster-postgres
volumes:
  dagster-postgres:
    driver: local
