# .gitlab-ci.yml

stages:
  - build
  - test
  - cleanup

variables:
  DOCKER_COMPOSE_FILE: docker-compose.yml

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose -f $DOCKER_COMPOSE_FILE build

test:
  stage: test
  image: python:3.9
  services:
    - docker:dind
  script:
    - docker-compose -f $DOCKER_COMPOSE_FILE up -d
    - pip install -r requirements-dev.txt
    - pip install -r requirements.txt
    - pytest ./ownerproject/tests/  # tests are in the "tests" directory
  only:
    - master
  
cleanup:
  stage: cleanup
  image: docker/compose:1.29.2
  script:
    - docker-compose -f $DOCKER_COMPOSE_FILE down
  only:
    - master